### ISSUE TITLE
Add docstrings in structures.py

### ISSUE THREAD

**Issue by yesseruser** [quintindunn/lapsepy#17]
> If you can, adding some docstrings would be amazing! If not don't worry I can do that later.

As originally posted by @quintindunn in https://github.com/quintindunn/lapsepy/pull/13#issuecomment-1775774787
Add docstrings to functions in structures.py

**Comment by quintindunn** [comment]
Added in commit: 4425aa38b4e7e58207eccb43c7c0bbd1c3d721eb
